### ISSUE TITLE
Diagram needed to show how OPA and CFN hooks connect

### ISSUE THREAD

**Issue by peteroneilljr** [StyraInc/opa-aws-cloudformation-hook#27]
For the readme, we should have a diagram that shows how data flows from AWS to OPA and back.

**Comment by anderseknert** [comment]
Added a diagram. Image wouldn't show up in a PR as relative links apparently don't resolve in those, so I had to push to main directly. Let me know what you think!

**Comment by peteroneilljr** [comment]
Looks great!
