### ISSUE TITLE
AWS Secrets Manager Bearer Token Value Parsing

### ISSUE THREAD

**Issue by jimmyraywv** [StyraInc/opa-aws-cloudformation-hook#35]
Does the AWS Secrets Manager bearer token value need parsing? Your code:

https://github.com/StyraInc/opa-aws-cloudformation-hook/blob/main/hooks/src/styra_opa_hook/handlers.py#L28-L44

Returns the `SecretString` from SecretsManager: `{"opa_auth_token": "<VALUE>"}`.

Are you expecting that entire string `{"opa_auth_token": "<VALUE>"}` to be configured in the OPA sever token auth? Or do we need to parse the actual value out with something like:

    `if 'SecretString' in resp:
        return list(json.loads(resp['SecretString']).values())[0]`

**Comment by anderseknert** [comment]
Hi Jimmy! The `SecretString` is expected to be the token itself, not presented as a key/value JSON object. I tried to express this in the [docs](https://www.openpolicyagent.org/docs/latest/aws-cloudformation-hooks/#opa-aws-cloudformation-hook-configuration): 

> Note that the token should be provided as a plain string in the secret (i.e. the SecretString) and not wrapped in a JSON object.

But perhaps it could be phrased better? 🤔

**Comment by jimmyraywv** [comment]
So, if you use the plain-text, and not the key/value fields then it should work, for a value with no key. I guess the `secret key must be 'opa_auth_token')` confused me.

**Comment by anderseknert** [comment]
Ah, yes, that's probably from an older iteration! Thanks for pointing that out 👍 Do you want to submit a PR to remove that or should I?

**Comment by anderseknert** [comment]
Fixed in #42. Thanks @pauly4it 👍
