### ISSUE TITLE
No Hook logging to CloudWatch logs

### ISSUE THREAD

**Issue by maslick** [StyraInc/opa-aws-cloudformation-hook#36]
This issue is connected with https://stackoverflow.com/questions/72526742/cloudformation-hooks-do-not-push-logs-to-cloudwatch-logs

**Comment by anderseknert** [comment]
That's interesting. The logs showed up in CloudWatch for me when I last tested the hook. I did not provide any custom configuration for cloudwatch, just went with whatever was generated by the init command.

**Comment by maslick** [comment]
The issue with me was that I forgot to specify log level:
```Python
LOG.setLevel(logging.INFO)
```

**Comment by anderseknert** [comment]
Ah! Thanks for following up 👍
